# Generated by Django 5.2 on 2025-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='muscle',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('full body', 'Full Body')], max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='start',
            field=models.TimeField(),
        ),
    ]
