# Generated by Django 5.2 on 2025-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_exercice_muscle_alter_workout_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
