# Generated by Django 5.1.7 on 2025-05-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_workout_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
