# Generated by Django 5.1.7 on 2025-05-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_workout_duration_workout_workout_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='ranting',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workout',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
