# Generated by Django 5.1.7 on 2025-05-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_workout_ranting_workout_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='ranting',
        ),
        migrations.AddField(
            model_name='workout',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
    ]
